<a href="https://colab.research.google.com/github/AdamayB/Tensorflow_Zero_to_Mastery/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Learning to about and making tensors using Tensorflow

Topics covered:

* Intro to tensors
* Getting info from tensors
* Manipulate tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up regular Python Functions)
* Using GPUs with TF(or TPUs)
* Excercise

# Intro to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#Creating Tensors
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Checking dimensions of a tensor
scalar.ndim

0

In [4]:
# Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimension of vector
vector.ndim

1

In [6]:
# Create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype = tf.float16) # specify data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Creating a tensor

tensor= tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we have created so far:
* Scalar: A single number
* Vector: A number with direction (e.g. wind speed and direction). Basically a list
* Matrix: A 2-dimensional array of numbers
* Tensor: An n-dimensional array of numbers (where n is any whole number)

### Creating tensors with tf.Variable

In [12]:
# Creating same tensors as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [15]:
# Trying .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [17]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

**Can't change this tensor**

In [19]:
unchangeable_tensor[0]=7
unchangeable_tensor

TypeError: ignored

In [22]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor()

AttributeError: ignored

### Creating Random Tensors

Random tensors are tensors of arbitrary size which contain random numbers

In [23]:
# 2 random tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [24]:
# Shuffle a tensor(used when you need to shuffle the data so that the inherent order doesn't affect learning)
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
tf.random.shuffle(not_shuffled) #shuffling along the first dimension only for example here shuffling along the rows

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [25]:
tf.random.shuffle(not_shuffled,seed=42) # does not give same results

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

* If only global seed is set, we get the same results.
* If global seed and operational seed is set, we get the same results.
* If only operational seed specified we get different result every time.


In [26]:
tf.random.set_seed(42) #global seed
tf.random.shuffle(not_shuffled,seed=42) # operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make Tensors

In [27]:
# Tensor of all zeros
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
# Tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays int tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can run on a GPU. Otherwise, they are same.

In [29]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [30]:
A=tf.constant(numpy_A)
B=tf.constant(numpy_A,shape=[2,3,4]) #2*3*4=24 must multiply and be equal to number of elements
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

# Getting info from tensors
Attributes of tensors:
* Shape
* Rank
* Axis or dimension
* Size

In [31]:
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
print("Datatype of all elements:",rank_4_tensor.dtype)
print("Number of Dimensions:",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Size of Tensors:",tf.size(rank_4_tensor))
print("Size of Tensors:",tf.size(rank_4_tensor).numpy())
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])

Datatype of all elements: <dtype: 'float32'>
Number of Dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Size of Tensors: tf.Tensor(120, shape=(), dtype=int32)
Size of Tensors: 120
Elements along the 0 axis: 2
Elements along the last axis: 5


### Indexing Tensors
Indexing just like lists

In [34]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])

In [37]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [38]:
rank_2_tensor[:,-1] # Last element of each row

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [39]:
# Adding dimensions
rank_3_tensor=rank_2_tensor[...,tf.newaxis] # Same as writing [:.:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
# Adding dimensions Method 2
tf.expand_dims(rank_2_tensor,axis=-1) # -1 = Last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

# Manipulating Tensors
Basic Operations:

+,  -,  *,  /

In [42]:
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [43]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [44]:
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [45]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [46]:
# to run faster on GPU use this
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication

In [47]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [48]:
#Python symbol
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [49]:
# Creating Tensor (3,2) tensor
X= tf.constant([[1,2],
                [3,4],
                [5,6]])

#Create another
Y= tf.constant([[7,8],
                [9,10],
                [11,12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [51]:
X@Y

InvalidArgumentError: ignored

In [53]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [54]:
X.shape

TensorShape([3, 2])

In [55]:
Y.shape

TensorShape([3, 2])

In [56]:
tf.reshape(Y,shape=(2,3)).shape

TensorShape([2, 3])

In [57]:
X@tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [58]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

### Changing Datatype of a Tensor

In [59]:
B=tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [60]:
C=tf.constant([7, 10])
C.dtype

tf.int32

In [61]:
# Change from float32 to float16 (reduced precision)
B=tf.cast(B, dtype=tf.float16)
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [62]:
C=tf.cast(C, dtype=tf.float16)
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

In [63]:
E=tf.cast(C, dtype=tf.int16)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>,
 tf.int16)

### Aggregating Tensors
Aggregating tensors = condensing them fro multiple values down to a smaller values

In [64]:
# Absolute value
D=tf.constant([-7,-10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

#### Forms of aggregations
* Get Min
* Get Max
* Get the mean of a tensor
* Get the sum of a tensor

In [65]:
U=tf.constant(np.random.randint(0,100,size=50))
U

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([25, 53, 32, 31, 29, 27, 65, 80, 49, 44, 52, 50, 76, 17, 28, 42, 18,
       39, 65, 59, 23, 28, 76, 29, 87, 81, 98, 66, 90,  4, 38, 10, 53, 29,
       30, 52, 89,  8, 14, 36, 40,  5, 84, 47, 62,  6, 87, 32, 74, 92])>

In [66]:
# Find the minimum
tf.reduce_min(U)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [67]:
# Find max
tf.reduce_max(U)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [68]:
# Find Mean
tf.reduce_mean(U)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [69]:
# Find sum
tf.reduce_sum(U)

<tf.Tensor: shape=(), dtype=int64, numpy=2351>

In [70]:
tf.reduce_prod(U)

<tf.Tensor: shape=(), dtype=int64, numpy=-4647714815446351872>

In [71]:
# Variance of tensor
import tensorflow_probability as tfp
tfp.stats.variance(U)

<tf.Tensor: shape=(), dtype=int64, numpy=689>

In [72]:
# Standard Deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

In [73]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.25>

### Positional Maximum and Minimum

In [74]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [75]:
# Finding positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [76]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [77]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [78]:
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [79]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [80]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor(removing all single dimensions)

In [81]:
# Create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [82]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One Hot Encoding Tensors

In [83]:
some_list=[0, 1, 2, 3]

# One hot encode indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [84]:
tf.one_hot(some_list,depth=5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [85]:
# Custom one hot encoding values
tf.one_hot(some_list, depth=4, on_value="I love Dua Lipa",off_value="I don't")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love Dua Lipa', b"I don't", b"I don't", b"I don't"],
       [b"I don't", b'I love Dua Lipa', b"I don't", b"I don't"],
       [b"I don't", b"I don't", b'I love Dua Lipa', b"I don't"],
       [b"I don't", b"I don't", b"I don't", b'I love Dua Lipa']],
      dtype=object)>

### Squaring, log, square root

In [86]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [87]:
# Squaring
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [88]:
# Find squareroot (won't work with dtype=int32)

tf.sqrt(tf.cast(H, dtype=tf.float32)) #Change the dtype to float32

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [89]:
# Find the log
#tf.math.log(H) would give error as dtype!=int32
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and NumPy
Tensorflow loves NumPy

In [90]:
# Create a Tensor using NumPy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [91]:
# Tensor to numpy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [92]:
# Tensor to NumPy
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [93]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [94]:
# Checking default dtypes
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Tensors can be used on GPUs and TPUs for faster numerical processing, this is the only difference between numpy and Tensorflow

### Finding access to GPUs

In [2]:
# When shifting to GPU runtime, runtime restars so we need to import tensorflow again
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Thu Jun 29 12:48:56 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------